name: 'Test typescript-action'
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          milliseconds: 1000
          github-token: '${{ secrets.GITHUB_TOKEN }}'
